Desafio/Models/DbContext.cs
namespace Desafio.Models
{
    public class DbContext
    {
    }
}

Desafio/Models/DbSet.cs
namespace Desafio.Models
{
    public class DbSet<Personas>
    {
    }
}

Desafio/Models/Personas.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Data;
using System.Web.ModelBinding;
using System.Web.Mvc;

namespace Desafio.Models
{
    public class Personas
    {
        public int ID_PERSONAS { get; set; }
        public string Nombre { get; set; }
        public char A_Paterno { get; set; }
        public char A_Materno { get; set; }
        public int Edad { get; set; }
        public bool Activo { get; set; }

    }
    public class PersonasDBContext : DbContext
    {
        public DbSet<Personas> Personas { get; set; }
    }

    public ActionResult Create([Bind(Include = "Nombre,A_Paterno,A_Materno,Edad,Activo")] Persona)
    {
        try
        {
            if (System.Web.ModelBinding.ModelState.IsValid)
            {
                Personas.Add(Persona);
                SaveChanges();
                return RedirectToAction("Index");
            }
        }
        catch (DataException /* dex */)
        {
            //Log the error (uncomment dex variable name and add a line here to write a log.
            System.Web.ModelBinding.ModelState.AddModelError("", "Unable to save changes. Try again, and if the problem persists see your system administrator.");
        }
        return View(Persona);
    }

Desafio/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Desafio.Controllers
{
    public class HomeController : Controller
    {
        private object db;

        public ActionResult Index()
        {
            return View(db.Persona.ToList());
        }

        private ActionResult View(object p)
        {
            throw new NotImplementedException();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Desafio/Controllers/PersonaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Net;

namespace Desafio.Controllers
{
    public class PersonaController : Controller
    {
        private object db;

        // GET: Persona
        public ActionResult Index()
        {
            return View();
        }

        // GET: Persona/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Persona/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Persona/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            try
            {
                // TODO: Add insert logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Persona/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Persona/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Persona/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Persona/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }

            public ActionResult Details(int?)
            {

                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                PERSONASEntities Persona = db.Personas.Find(id);

                if (Persona == null)

                {
                    return HttpNotFound();
                }
                return View(Persona);
            }
        }
    }
}

Desafio/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Desafio/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Desafio/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.A_Paterno)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.A_Materno)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Edad)
        </th>

        <th>
            @Html.DisplayNameFor(model => model.Acivo)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
<tr>
    <th>
        @Html.DisplayNameFor(model => model.Nombre)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.A_Paterno)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.A_Materno)
    </th>
    <th>
        @Html.DisplayNameFor(model => model.Edad)
    </th>

    <th>
        @Html.DisplayNameFor(model => model.Acivo)
    </th>

    <td>
        @Html.ActionLink("Edit", "Edit", new { id = item.ID_PERSONAS }) |
        @Html.ActionLink("Details", "Details", new { id = item.ID_PERSONAS }) |
        @Html.ActionLink("Delete", "Delete", new { id = item.ID_PERSONAS })
    </td>
</tr>

Desafio/Views/Persona/ViewPersona.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title></title>
</head>
<body>
    <div>

    </div>
    <dt>
        @Html.DisplayNameFor(model => model.A_Paterno)
    </dt>
    <dd>
        @Html.DisplayFor(model => model.A_Materno)
    </dd>
</body>
</html>

Desafio/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Personas</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    </head>>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="navbar-inner">
                <div class="container">
                    <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    @Html.ActionLink("Contoso Universi", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
                    <div class="nav-collapse collapse">
                        <ul class="nav">
                            <li>@Html.ActionLink("Personas", "Index", "Persona")</li>
                            <
                        </ul>
                    </div>
                </div>
            </div>
        </div>

        <div class="container">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; @DateTime.Now.Year - Contoso University</p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>
</html>